// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rLycm7fJPyjpC5eVgPhFFv
// Component: QshPVMO6JzXS

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Header from "../../Header"; // plasmic-import: lTFHprYmdK/component
import Footer from "../../Footer"; // plasmic-import: kLiRdGmg5zv/component

import { useScreenVariants as useScreenVariantsqqPMw8O9H4JqN } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: qqPMw8o9H4jqN/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_pg_staking.module.css"; // plasmic-import: rLycm7fJPyjpC5eVgPhFFv/projectcss
import sty from "./PlasmicDonationTermsConditions.module.css"; // plasmic-import: QshPVMO6JzXS/css

createPlasmicElementProxy;

export type PlasmicDonationTermsConditions__VariantMembers = {};
export type PlasmicDonationTermsConditions__VariantsArgs = {};
type VariantPropType = keyof PlasmicDonationTermsConditions__VariantsArgs;
export const PlasmicDonationTermsConditions__VariantProps =
  new Array<VariantPropType>();

export type PlasmicDonationTermsConditions__ArgsType = {};
type ArgPropType = keyof PlasmicDonationTermsConditions__ArgsType;
export const PlasmicDonationTermsConditions__ArgProps =
  new Array<ArgPropType>();

export type PlasmicDonationTermsConditions__OverridesType = {
  root?: Flex__<"div">;
  header?: Flex__<typeof Header>;
  h1?: Flex__<"h1">;
  h4?: Flex__<"h4">;
  footer?: Flex__<typeof Footer>;
};

export interface DefaultDonationTermsConditionsProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicDonationTermsConditions__RenderFunc(props: {
  variants: PlasmicDonationTermsConditions__VariantsArgs;
  args: PlasmicDonationTermsConditions__ArgsType;
  overrides: PlasmicDonationTermsConditions__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsqqPMw8O9H4JqN()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">
          {PlasmicDonationTermsConditions.pageMetadata.title}
        </title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicDonationTermsConditions.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicDonationTermsConditions.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__naoLb)}>
            <Header
              data-plasmic-name={"header"}
              data-plasmic-override={overrides.header}
              activeUrl={"about"}
              className={classNames("__wab_instance", sty.header)}
            />

            <div className={classNames(projectcss.all, sty.freeBox__hiKxJ)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__qvE0Z)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__vJiGn)}
                >
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1
                    )}
                  >
                    {"Donation Terms & Conditions"}
                  </h1>
                </Stack__>
                <h4
                  data-plasmic-name={"h4"}
                  data-plasmic-override={overrides.h4}
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <h2
                        className={classNames(
                          projectcss.all,
                          projectcss.h2,
                          projectcss.__wab_text,
                          sty.h2__yHe1F
                        )}
                      >
                        {"Introduction"}
                      </h2>
                    }
                    <React.Fragment>{""}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"1.1"}
                    </span>
                    <React.Fragment>
                      {
                        " These terms and conditions govern Donor\u2019s (referred to as \u201c"
                      }
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"Donor"}
                    </span>
                    <React.Fragment>{'\u201d, "'}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"you"}
                    </span>
                    <React.Fragment>{'", "'}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"your"}
                    </span>
                    <React.Fragment>
                      {
                        '") use of Open Impact Foundation PCC\u2019s website and your interactions with Open Impact Foundation PCC and its respective cells (referred to as \u201c'
                      }
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"OIF"}
                    </span>
                    <React.Fragment>{'\u201d, "'}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"we"}
                    </span>
                    <React.Fragment>{'", "'}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"our"}
                    </span>
                    <React.Fragment>{'", or "'}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"us"}
                    </span>
                    <React.Fragment>
                      {
                        '"). By accessing or using our website and making donations to OIF and/or its respective cells, you agree to be bound by these terms and conditions in full. If you disagree with any part of these terms and conditions, you must not use our website or make donations.\n\n'
                      }
                    </React.Fragment>
                    {
                      <h2
                        className={classNames(
                          projectcss.all,
                          projectcss.h2,
                          projectcss.__wab_text,
                          sty.h2__h83P1
                        )}
                      >
                        {"Definitions"}
                      </h2>
                    }
                    <React.Fragment>{""}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"2.1"}
                    </span>
                    <React.Fragment>
                      {
                        " Donor: Any individual or entity making a donation to the Open Impact Foundation PCC or its respective cells.\n"
                      }
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"2.2"}
                    </span>
                    <React.Fragment>
                      {
                        " OIF: Open Impact Foundation PCC, a charitable foundation organized and existing under the laws of Liechtenstein.\n"
                      }
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"2.3"}
                    </span>
                    <React.Fragment>
                      {
                        " Cell: A specific program or initiative with its own legal personality operated by OIF for charitable purposes.\n"
                      }
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"2.4"}
                    </span>
                    <React.Fragment>
                      {
                        " Legal Tender: Fiat currency recognized as legal tender by the jurisdiction in which the donation is made.\n"
                      }
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"2.5"}
                    </span>
                    <React.Fragment>
                      {
                        " Cryptocurrencies: Digital assets, including but not limited to Bitcoin, Ethereum, and other blockchain-based tokens.\n"
                      }
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"2.6"}
                    </span>
                    <React.Fragment>
                      {
                        " Decentralized Protocols: Blockchain-based systems or networks governed by consensus mechanisms rather than central authorities.\n\n"
                      }
                    </React.Fragment>
                    {
                      <h2
                        className={classNames(
                          projectcss.all,
                          projectcss.h2,
                          projectcss.__wab_text,
                          sty.h2__e8DzR
                        )}
                      >
                        {"Donations"}
                      </h2>
                    }
                    <React.Fragment>{""}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"3.1"}
                    </span>
                    <React.Fragment>
                      {
                        " OIF and its respective cell, to which you dedicate your donation, accepts donations in legal tender (fiat currency) as well as cryptocurrencies. The accepted legal tender and cryptocurrencies will be shown to you as part of the donation process.\n"
                      }
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"3.2"}
                    </span>
                    <React.Fragment>
                      {
                        " OIF will inform you to which cell you are donating as part of the donation process. As part of this, you will also be informed of the exact charitable purpose of the cell to which you are donating.\n"
                      }
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"3.3"}
                    </span>
                    <React.Fragment>
                      {
                        " Donations made in cryptocurrencies may include such received through decentralized protocols where OIF and its respective cell receives a portion of cryptocurrency to be staked and/or staking rewards due to smart contract involvement. Such donations are considered valid contributions to OIF and its respective cell\u2019s charitable purposes. For the avoidance of doubt, neither OIF nor any of its cells are attributable to such decentralized protocols and/or smart contracts, neither OIF nor any of its cells provide services in connection with staking; OIF and/or its cells can only be donated via such decentralized protocols and/or smart contracts that are open source and have been published by whomever, but not by OIF or any of its cells.\n"
                      }
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"3.4"}
                    </span>
                    <React.Fragment>
                      {
                        " Donors making contributions through decentralized protocols and/or smart contracts understand and acknowledge the inherent risks associated with such transactions, including but not limited to smart contract vulnerabilities, market volatility, impermanent loss, etc.\n\n"
                      }
                    </React.Fragment>
                    {
                      <h2
                        className={classNames(
                          projectcss.all,
                          projectcss.h2,
                          projectcss.__wab_text,
                          sty.h2__tQ3ZJ
                        )}
                      >
                        {"Charitable Nature of Donations"}
                      </h2>
                    }
                    <React.Fragment>{""}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"4.1"}
                    </span>
                    <React.Fragment>
                      {
                        " By donating to OIF and its respective cell, you acknowledge and agree that your donation is made for charitable purposes.\n"
                      }
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"4.2"}
                    </span>
                    <React.Fragment>
                      {
                        " You recognize that your donation is irrevocable once accepted. You waive any grounds for avoidance, irrespective of the legal basis, in particular on the grounds of error or poverty.\n"
                      }
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"4.3"}
                    </span>
                    <React.Fragment>
                      {
                        " You understand and accept that you will not receive anything in return for your donation, except for a receipt for the contact information you provide in the donation process upon our acceptance of the donation.\n\n"
                      }
                    </React.Fragment>
                    {
                      <h2
                        className={classNames(
                          projectcss.all,
                          projectcss.h2,
                          projectcss.__wab_text,
                          sty.h2__gF2B7
                        )}
                      >
                        {"Use of Donations"}
                      </h2>
                    }
                    <React.Fragment>{""}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"5.1"}
                    </span>
                    <React.Fragment>
                      {
                        " OIF and its respective cells will utilize donations for the intended charitable purposes as outlined by our mission and objectives and as shown to you in the donation process.\n"
                      }
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"5.2"}
                    </span>
                    <React.Fragment>
                      {
                        " We commit to transparency and accountability in the use of donated funds, subject to monitoring by relevant state authorities.\n"
                      }
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"5.3"}
                    </span>
                    <React.Fragment>
                      {
                        " Donors acknowledge that OIF and its respective cells cannot guarantee the specific allocation or outcome of their donations due to changing circumstances and priorities in charitable projects.\n\n"
                      }
                    </React.Fragment>
                    {
                      <h2
                        className={classNames(
                          projectcss.all,
                          projectcss.h2,
                          projectcss.__wab_text,
                          sty.h2__lqVRg
                        )}
                      >
                        {"Donor Obligations"}
                      </h2>
                    }
                    <React.Fragment>{""}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"6.1"}
                    </span>
                    <React.Fragment>
                      {
                        " By making a donation, you agree to cooperate with OIF and its respective cells and provide necessary information regarding compliance upon our request.\n"
                      }
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"6.2"}
                    </span>
                    <React.Fragment>
                      {
                        " Specific compliance requirements may vary depending on factors such as the amount of the donation, whether the donor is a natural or legal person, etc.\n"
                      }
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"6.3"}
                    </span>
                    <React.Fragment>
                      {
                        " Failure to cooperate with compliance requests may result in the rejection of the donation.\n\n"
                      }
                    </React.Fragment>
                    {
                      <h2
                        className={classNames(
                          projectcss.all,
                          projectcss.h2,
                          projectcss.__wab_text,
                          sty.h2__xIbeA
                        )}
                      >
                        {"Acknowledgment"}
                      </h2>
                    }
                    <React.Fragment>{""}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"7.1"}
                    </span>
                    <React.Fragment>
                      {
                        " By sending a donation to OIF and its respective cell, you acknowledge and agree to these terms and conditions. You confirm that you have informed yourself about the legal and organizational form and the charitable purpose of OIF and its cells.\n"
                      }
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"7.2"}
                    </span>
                    <React.Fragment>
                      {
                        " You will receive a receipt for the contact information you provided once OIF and its cell has accepted the donation, contingent upon successful completion in particular of all compliance procedures.\n\n"
                      }
                    </React.Fragment>
                    {
                      <h2
                        className={classNames(
                          projectcss.all,
                          projectcss.h2,
                          projectcss.__wab_text,
                          sty.h2__lwn7H
                        )}
                      >
                        {"Legal Compliance"}
                      </h2>
                    }
                    <React.Fragment>{""}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"8.1"}
                    </span>
                    <React.Fragment>
                      {
                        " Donors are responsible for ensuring compliance with all applicable laws, regulations, and tax requirements related to their donations, including but not limited to anti-money laundering (AML) and know your customer (KYC) regulations.\n"
                      }
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"8.2"}
                    </span>
                    <React.Fragment>
                      {
                        " OIF and its cells reserve the right to request additional information or documentation from donors to verify compliance with legal and regulatory requirements, and failure to provide such information may result in the rejection of the donation.\n\n"
                      }
                    </React.Fragment>
                    {
                      <h2
                        className={classNames(
                          projectcss.all,
                          projectcss.h2,
                          projectcss.__wab_text,
                          sty.h2__cmAy
                        )}
                      >
                        {"Risk Information"}
                      </h2>
                    }
                    <React.Fragment>{""}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"9.1"}
                    </span>
                    <React.Fragment>
                      {
                        " Donors should be aware that the value of cryptocurrencies can be volatile, and their donation amounts may fluctuate when received by OIF and its cells. OIF and its cells do not hedge against fluctuations, and donors bear the risk of loss associated with such volatility.\n"
                      }
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"9.2"}
                    </span>
                    <React.Fragment>
                      {
                        " Donors acknowledge and understand the risks associated with transactions made through decentralized protocols and smart contracts, including but not limited to potential smart contract vulnerabilities, loss of funds due to coding errors, and market volatility.\n"
                      }
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"9.3"}
                    </span>
                    <React.Fragment>
                      {
                        " OIF and its cells advise donors to conduct thorough due diligence and seek independent financial and legal advice before making donations, especially those involving cryptocurrencies or decentralized protocols. Donors are responsible for ensuring the legality of their donations and compliance with relevant laws in their jurisdiction and OIF and its cells\u2019 jurisdiction.\n"
                      }
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"9.4"}
                    </span>
                    <React.Fragment>
                      {
                        " OIF and its cells are not liable for any loss or damages incurred by donors as a result of their donations, including but not limited to loss of value, regulatory penalties, or tax liabilities.\n\n"
                      }
                    </React.Fragment>
                    {
                      <h2
                        className={classNames(
                          projectcss.all,
                          projectcss.h2,
                          projectcss.__wab_text,
                          sty.h2___7Vogg
                        )}
                      >
                        {"Indemnification"}
                      </h2>
                    }
                    <React.Fragment>{""}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"10.1"}
                    </span>
                    <React.Fragment>
                      {
                        " Donors agree to indemnify, defend, and hold harmless OIF and its cells, their directors, officers, employees, and agents from and against any and all claims, losses, damages, liabilities, and expenses arising out of or in connection with the donor's donation or breach of these terms and conditions.\n\n"
                      }
                    </React.Fragment>
                    {
                      <h2
                        className={classNames(
                          projectcss.all,
                          projectcss.h2,
                          projectcss.__wab_text,
                          sty.h2__wqktH
                        )}
                      >
                        {"Data Protection"}
                      </h2>
                    }
                    <React.Fragment>{""}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"11.1"}
                    </span>
                    <React.Fragment>
                      {
                        " By making a donation, donors consent to the collection, processing, and storage of their personal information by OIF and its cells for the purpose of facilitating and administering the donation process. By donating, you expressly recognise our privacy policy.\n"
                      }
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"11.2 "}
                    </span>
                    <React.Fragment>
                      {
                        "OIF and its cells will handle donor information in compliance with applicable data protection laws, including the General Data Protection Regulation (GDPR), and will not disclose donor information to third parties without explicit consent, except as required by law.\n\n"
                      }
                    </React.Fragment>
                    {
                      <h2
                        className={classNames(
                          projectcss.all,
                          projectcss.h2,
                          projectcss.__wab_text,
                          sty.h2__hb1Sz
                        )}
                      >
                        {"General"}
                      </h2>
                    }
                    <React.Fragment>{""}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"12.1"}
                    </span>
                    <React.Fragment>
                      {
                        " These terms and conditions constitute the entire agreement between you and OIF its respective cell regarding your use of our website and your donations to its respective cell, to which you donate.\n"
                      }
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"12.2"}
                    </span>
                    <React.Fragment>
                      {
                        " We reserve the right to amend or update these terms and conditions at any time without prior notice.\n"
                      }
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"12.3"}
                    </span>
                    <React.Fragment>
                      {
                        " Your continued use of our website and making donations after any changes to these terms and conditions constitutes acceptance of those changes.\n\n"
                      }
                    </React.Fragment>
                    {
                      <h2
                        className={classNames(
                          projectcss.all,
                          projectcss.h2,
                          projectcss.__wab_text,
                          sty.h2__o9Jq8
                        )}
                      >
                        {"Severability"}
                      </h2>
                    }
                    <React.Fragment>{""}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"13.1"}
                    </span>
                    <React.Fragment>
                      {
                        " If any provision of these terms and conditions is held to be invalid, illegal, or unenforceable by a court of competent jurisdiction, the validity, legality, and enforceability of the remaining provisions shall not in any way be affected or impaired thereby, and the parties shall replace the invalid, illegal, or unenforceable provision with a valid, legal, and enforceable provision that most closely reflects the original intention of the parties.\n\n"
                      }
                    </React.Fragment>
                    {
                      <h2
                        className={classNames(
                          projectcss.all,
                          projectcss.h2,
                          projectcss.__wab_text,
                          sty.h2__jDuWr
                        )}
                      >
                        {"Choice of Law and Jurisdiction Clause"}
                      </h2>
                    }
                    <React.Fragment>{""}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"14.1"}
                    </span>
                    <React.Fragment>
                      {
                        " Any disputes arising out of or in connection with these terms and conditions, including disputes regarding the validity, interpretation, or termination thereof, shall be exclusively governed by and construed in accordance with the laws of Liechtenstein, without regard to its conflict of law provisions and under exclusion of the UN-Sales-Convention.\n"
                      }
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"14.2"}
                    </span>
                    <React.Fragment>
                      {
                        " The parties hereby submit to the exclusive jurisdiction of the courts of Liechtenstein for the resolution of any such disputes.\n\n\nIf you have any questions or concerns about these terms and conditions, please contact us at "
                      }
                    </React.Fragment>
                    {
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link__mEyhy
                        )}
                        component={Link}
                        href={"mailto:hello@openimpact.foundation"}
                        platform={"nextjs"}
                      >
                        {"hello@openimpact.foundation"}
                      </PlasmicLink__>
                    }
                    <React.Fragment>
                      {
                        "\n\nOpen Impact Foundation PCC\nc/o SCHREIBER & ZINDEL Treuhand-Anstalt\nKirchstrasse 39\n9490 Vaduz\nPrincipality of Liechtenstein\n"
                      }
                    </React.Fragment>
                    {
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link__jhW2D
                        )}
                        component={Link}
                        href={"https://openimpact.foundation"}
                        platform={"nextjs"}
                      >
                        {"www.openimpact.foundation"}
                      </PlasmicLink__>
                    }
                    <React.Fragment>{" \n"}</React.Fragment>
                  </React.Fragment>
                </h4>
              </Stack__>
            </div>
            <Footer
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames("__wab_instance", sty.footer)}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "header", "h1", "h4", "footer"],
  header: ["header"],
  h1: ["h1"],
  h4: ["h4"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: typeof Header;
  h1: "h1";
  h4: "h4";
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicDonationTermsConditions__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicDonationTermsConditions__VariantsArgs;
    args?: PlasmicDonationTermsConditions__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicDonationTermsConditions__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicDonationTermsConditions__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicDonationTermsConditions__ArgProps,
          internalVariantPropNames: PlasmicDonationTermsConditions__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicDonationTermsConditions__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicDonationTermsConditions";
  } else {
    func.displayName = `PlasmicDonationTermsConditions.${nodeName}`;
  }
  return func;
}

export const PlasmicDonationTermsConditions = Object.assign(
  // Top-level PlasmicDonationTermsConditions renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    h1: makeNodeComponent("h1"),
    h4: makeNodeComponent("h4"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicDonationTermsConditions
    internalVariantProps: PlasmicDonationTermsConditions__VariantProps,
    internalArgProps: PlasmicDonationTermsConditions__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Public Goods Funding - Terms & Conditions",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicDonationTermsConditions;
/* prettier-ignore-end */
