// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rLycm7fJPyjpC5eVgPhFFv
// Component: hDCtDazGctA

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: lTFHprYmdK/component
import Footer from "../../Footer"; // plasmic-import: kLiRdGmg5zv/component

import { useScreenVariants as useScreenVariantsqqPMw8O9H4JqN } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: qqPMw8o9H4jqN/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_pg_staking.module.css"; // plasmic-import: rLycm7fJPyjpC5eVgPhFFv/projectcss
import sty from "./PlasmicFaQs.module.css"; // plasmic-import: hDCtDazGctA/css

createPlasmicElementProxy;

export type PlasmicFaQs__VariantMembers = {};
export type PlasmicFaQs__VariantsArgs = {};
type VariantPropType = keyof PlasmicFaQs__VariantsArgs;
export const PlasmicFaQs__VariantProps = new Array<VariantPropType>();

export type PlasmicFaQs__ArgsType = {};
type ArgPropType = keyof PlasmicFaQs__ArgsType;
export const PlasmicFaQs__ArgProps = new Array<ArgPropType>();

export type PlasmicFaQs__OverridesType = {
  root?: p.Flex<"div">;
  header?: p.Flex<typeof Header>;
  h6?: p.Flex<"h6">;
  footer?: p.Flex<typeof Footer>;
};

export interface DefaultFaQsProps {}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicFaQs__RenderFunc(props: {
  variants: PlasmicFaQs__VariantsArgs;
  args: PlasmicFaQs__ArgsType;
  overrides: PlasmicFaQs__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants,
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsqqPMw8O9H4JqN(),
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicFaQs.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicFaQs.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicFaQs.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__aUgK1)}>
            <Header
              data-plasmic-name={"header"}
              data-plasmic-override={overrides.header}
              activeUrl={"faQs" as const}
              className={classNames("__wab_instance", sty.header)}
            />

            <div className={classNames(projectcss.all, sty.freeBox___3YbeX)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__btntn)}
              >
                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__j7T5V)}
                  >
                    <h6
                      data-plasmic-name={"h6"}
                      data-plasmic-override={overrides.h6}
                      className={classNames(
                        projectcss.all,
                        projectcss.h6,
                        projectcss.__wab_text,
                        sty.h6
                      )}
                    >
                      {"FAQs"}
                    </h6>
                  </p.Stack>
                ) : null}
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns__hfRm)}
                >
                  {(
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? true
                      : true
                  ) ? (
                    <div
                      className={classNames(projectcss.all, sty.column__w2FZz)}
                    >
                      {true ? (
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__yPPoI
                          )}
                        >
                          {true ? (
                            <p.Stack
                              as={"div"}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__ih7Ze
                              )}
                            >
                              {true ? (
                                <p.Stack
                                  as={"div"}
                                  hasGap={true}
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox___5Hrgw
                                  )}
                                >
                                  <h2
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.h2,
                                      projectcss.__wab_text,
                                      sty.h2___6Rx5D
                                    )}
                                  >
                                    {"What is Public Goods (PG) Leasing?"}
                                  </h2>
                                  <h4
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.h4,
                                      projectcss.__wab_text,
                                      sty.h4___5EQ9C
                                    )}
                                  >
                                    {
                                      "PG staking \u201cLeasing\u201d is currently running for FIL holders. We utilize GLIF. GLIF is a non-custodial automated leasing pool designed for the Filecoin network. It offers eligible Filecoin Storage Providers a convenient way to borrow FIL up to the value of the collateral they contribute to the pool. Storage Providers will make automated weekly payments back into pools, with payment amounts dynamically determined based on current market conditions. For the Public good pools-  rewards will be allocated to a public goods multisig, in which funding will be allocated by transparent on-chain tooling like Impact Evaluators and other governance tooling in a decentralized and transparent way which encourages active and clear allocation of support.  \n\n\nFollowing is an illustration of the automated Public Goods non-custodial leasing pool setup:"
                                    }
                                  </h4>
                                  <p.PlasmicImg
                                    alt={""}
                                    className={classNames(sty.img__l88Vb)}
                                    displayHeight={"auto" as const}
                                    displayMaxHeight={"none" as const}
                                    displayMaxWidth={"100%" as const}
                                    displayMinHeight={"0" as const}
                                    displayMinWidth={"0" as const}
                                    displayWidth={"auto" as const}
                                    loading={"lazy" as const}
                                    src={{
                                      src: "/plasmic/pg_staking/images/glifBlogpost1Png2.png",
                                      fullWidth: 532,
                                      fullHeight: 379,
                                      aspectRatio: undefined,
                                    }}
                                  />
                                </p.Stack>
                              ) : null}
                              {true ? (
                                <p.Stack
                                  as={"div"}
                                  hasGap={true}
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__qJqHx
                                  )}
                                >
                                  <h2
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.h2,
                                      projectcss.__wab_text,
                                      sty.h2__erPl
                                    )}
                                  >
                                    {"Why do this on chain?"}
                                  </h2>
                                  <h4
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.h4,
                                      projectcss.__wab_text,
                                      sty.h4__rppUs
                                    )}
                                  >
                                    {
                                      "Traditional off chain models for funding include grants and funding allocation channels like crowdfunding, foundations and developer awards. These often lack transparency and are decided by a central entity. Payment times can vary from a few weeks to several months or even years. Community and ecosystem developers do not typically have access to the tracing or transparency of funding or what teams are allocated how much and when. The thesis of restructuring funding to onchain mechanism means that much of these delays and lack of transparency are theoretically eliminated. Once a voting round closes, team allocations are automatically done- this means that payments happen faster, teams can accelerate and scale accordingly without dependency on additional parties. "
                                    }
                                  </h4>
                                </p.Stack>
                              ) : null}
                              {true ? (
                                <p.Stack
                                  as={"div"}
                                  hasGap={true}
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__oFakw
                                  )}
                                >
                                  <h2
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.h2,
                                      projectcss.__wab_text,
                                      sty.h2__oA5Mb
                                    )}
                                  >
                                    {"What is iFil?"}
                                  </h2>
                                  <h4
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.h4,
                                      projectcss.__wab_text,
                                      sty.h4__qQF
                                    )}
                                  >
                                    <React.Fragment>
                                      <React.Fragment>
                                        {
                                          "When a FIL token holder deposits FIL into the Infinity Pool, they receive iFIL tokens in return. iFIL is the native liquid staking token for filecoin - iFIL can be transferred to other wallets, traded on secondaries, and used in other DeFi protocols. The price of iFIL is calculated as: \n     iFIL price = Glif Infinity Pool total assets / iFIL circulating supply \n\nThe initial price of iFIL to FIL is 1 : 1, but this will change once the borrowing side of the Infinity Pool opens to SPs. When the Infinity Pool receives its weekly payment from an SP, the Infinity Pool's total assets increase, which increases the value of iFIL in terms of FIL. When a Staker deposits FIL in the pool, they get back a proportionate amount of iFIL determined by the current iFIL price at that point in time:\n     "
                                        }
                                      </React.Fragment>
                                      <span
                                        className={
                                          "plasmic_default__all plasmic_default__span"
                                        }
                                        style={{ fontWeight: 700 }}
                                      >
                                        {
                                          "iFIL received = FIL stake / current iFIL price"
                                        }
                                      </span>
                                      <React.Fragment>
                                        {
                                          " \n\nAs the price of iFIL increases, the amount of iFIL received per FIL stake decreases."
                                        }
                                      </React.Fragment>
                                    </React.Fragment>
                                  </h4>
                                </p.Stack>
                              ) : null}
                              {true ? (
                                <p.Stack
                                  as={"div"}
                                  hasGap={true}
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox___9Akpu
                                  )}
                                >
                                  <h2
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.h2,
                                      projectcss.__wab_text,
                                      sty.h2__oOqLg
                                    )}
                                  >
                                    {"Process Description"}
                                  </h2>
                                  {true ? (
                                    <p.Stack
                                      as={"div"}
                                      hasGap={true}
                                      className={classNames(
                                        projectcss.all,
                                        sty.freeBox___2RRta
                                      )}
                                    >
                                      <p.PlasmicImg
                                        alt={""}
                                        className={classNames(sty.img__vZsxt)}
                                        displayHeight={"auto" as const}
                                        displayMaxHeight={"none" as const}
                                        displayMaxWidth={"none" as const}
                                        displayMinHeight={"0" as const}
                                        displayMinWidth={"0" as const}
                                        displayWidth={"auto" as const}
                                        loading={"lazy" as const}
                                        src={{
                                          src: "/plasmic/pg_staking/images/_1Svg.svg",
                                          fullWidth: 101,
                                          fullHeight: 150,
                                          aspectRatio: 0.673077,
                                        }}
                                      />

                                      <h4
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.h4,
                                          projectcss.__wab_text,
                                          sty.h4__dpLpV
                                        )}
                                      >
                                        {
                                          "FIL Holders transfer their FIL in a Public Goods Leasing Pool which is an allocation within the GLIF Infinity Pool"
                                        }
                                      </h4>
                                    </p.Stack>
                                  ) : null}
                                  {true ? (
                                    <p.Stack
                                      as={"div"}
                                      hasGap={true}
                                      className={classNames(
                                        projectcss.all,
                                        sty.freeBox__sgLan
                                      )}
                                    >
                                      <p.PlasmicImg
                                        alt={""}
                                        className={classNames(sty.img__uleRh)}
                                        displayHeight={"auto" as const}
                                        displayMaxHeight={"none" as const}
                                        displayMaxWidth={"none" as const}
                                        displayMinHeight={"0" as const}
                                        displayMinWidth={"0" as const}
                                        displayWidth={"auto" as const}
                                        loading={"lazy" as const}
                                        src={{
                                          src: "/plasmic/pg_staking/images/_2Svg.svg",
                                          fullWidth: 109,
                                          fullHeight: 150,
                                          aspectRatio: 0.72381,
                                        }}
                                      />

                                      <h4
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.h4,
                                          projectcss.__wab_text,
                                          sty.h4___7EySo
                                        )}
                                      >
                                        {
                                          "FIL will be borrowed to FIlecoin Storage Providers"
                                        }
                                      </h4>
                                    </p.Stack>
                                  ) : null}
                                  {true ? (
                                    <p.Stack
                                      as={"div"}
                                      hasGap={true}
                                      className={classNames(
                                        projectcss.all,
                                        sty.freeBox__vOdsI
                                      )}
                                    >
                                      <p.PlasmicImg
                                        alt={""}
                                        className={classNames(sty.img__ceVdH)}
                                        displayHeight={"auto" as const}
                                        displayMaxHeight={"none" as const}
                                        displayMaxWidth={"none" as const}
                                        displayMinHeight={"0" as const}
                                        displayMinWidth={"0" as const}
                                        displayWidth={"auto" as const}
                                        loading={"lazy" as const}
                                        src={{
                                          src: "/plasmic/pg_staking/images/_3Svg.svg",
                                          fullWidth: 108,
                                          fullHeight: 150,
                                          aspectRatio: 0.719626,
                                        }}
                                      />

                                      <h4
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.h4,
                                          projectcss.__wab_text,
                                          sty.h4__rklre
                                        )}
                                      >
                                        {
                                          "FIL rewards are paid out and the fee split determined by the holder will happen  automatically at time of distribution"
                                        }
                                      </h4>
                                    </p.Stack>
                                  ) : null}
                                  {true ? (
                                    <p.Stack
                                      as={"div"}
                                      hasGap={true}
                                      className={classNames(
                                        projectcss.all,
                                        sty.freeBox__ltjfA
                                      )}
                                    >
                                      <p.PlasmicImg
                                        alt={""}
                                        className={classNames(sty.img__eQ3IF)}
                                        displayHeight={"auto" as const}
                                        displayMaxHeight={"none" as const}
                                        displayMaxWidth={"none" as const}
                                        displayMinHeight={"0" as const}
                                        displayMinWidth={"0" as const}
                                        displayWidth={"auto" as const}
                                        loading={"lazy" as const}
                                        src={{
                                          src: "/plasmic/pg_staking/images/_4Svg.svg",
                                          fullWidth: 116,
                                          fullHeight: 150,
                                          aspectRatio: 0.771429,
                                        }}
                                      />

                                      <h4
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.h4,
                                          projectcss.__wab_text,
                                          sty.h4__jngxY
                                        )}
                                      >
                                        {
                                          "On-chain governance or voting by community will allocate funding utilizing Impact Evaluators to projects focusing on public goods on projects elected. To begin: IPFS, FVM and libp2p"
                                        }
                                      </h4>
                                    </p.Stack>
                                  ) : null}
                                </p.Stack>
                              ) : null}
                              {true ? (
                                <p.Stack
                                  as={"div"}
                                  hasGap={true}
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__wd3Q3
                                  )}
                                >
                                  <h2
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.h2,
                                      projectcss.__wab_text,
                                      sty.h2__dwrE
                                    )}
                                  >
                                    {"How do I participate?"}
                                  </h2>
                                  {true ? (
                                    <p.Stack
                                      as={"div"}
                                      hasGap={true}
                                      className={classNames(
                                        projectcss.all,
                                        sty.freeBox___5DaY6
                                      )}
                                    >
                                      <p.PlasmicImg
                                        alt={""}
                                        className={classNames(sty.img__hXdCs)}
                                        displayHeight={"auto" as const}
                                        displayMaxHeight={"none" as const}
                                        displayMaxWidth={"none" as const}
                                        displayMinHeight={"0" as const}
                                        displayMinWidth={"0" as const}
                                        displayWidth={"auto" as const}
                                        loading={"lazy" as const}
                                        src={{
                                          src: "/plasmic/pg_staking/images/_1Svg.svg",
                                          fullWidth: 101,
                                          fullHeight: 150,
                                          aspectRatio: 0.673077,
                                        }}
                                      />

                                      <h4
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.h4,
                                          projectcss.__wab_text,
                                          sty.h4__a66ID
                                        )}
                                      >
                                        {
                                          "Deposit FIL and receive an equal amount of iFIL tokens in return"
                                        }
                                      </h4>
                                    </p.Stack>
                                  ) : null}
                                  {true ? (
                                    <p.Stack
                                      as={"div"}
                                      hasGap={true}
                                      className={classNames(
                                        projectcss.all,
                                        sty.freeBox__kKwUw
                                      )}
                                    >
                                      <p.PlasmicImg
                                        alt={""}
                                        className={classNames(sty.img__aHBa1)}
                                        displayHeight={"auto" as const}
                                        displayMaxHeight={"none" as const}
                                        displayMaxWidth={"none" as const}
                                        displayMinHeight={"0" as const}
                                        displayMinWidth={"0" as const}
                                        displayWidth={"auto" as const}
                                        loading={"lazy" as const}
                                        src={{
                                          src: "/plasmic/pg_staking/images/_2Svg.svg",
                                          fullWidth: 109,
                                          fullHeight: 150,
                                          aspectRatio: 0.72381,
                                        }}
                                      />

                                      <h4
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.h4,
                                          projectcss.__wab_text,
                                          sty.h4__ndrYe
                                        )}
                                      >
                                        {"Your FIL will enter the staking pool"}
                                      </h4>
                                    </p.Stack>
                                  ) : null}
                                  {true ? (
                                    <p.Stack
                                      as={"div"}
                                      hasGap={true}
                                      className={classNames(
                                        projectcss.all,
                                        sty.freeBox__rUyjb
                                      )}
                                    >
                                      <p.PlasmicImg
                                        alt={""}
                                        className={classNames(sty.img___2EeXk)}
                                        displayHeight={"auto" as const}
                                        displayMaxHeight={"none" as const}
                                        displayMaxWidth={"none" as const}
                                        displayMinHeight={"0" as const}
                                        displayMinWidth={"0" as const}
                                        displayWidth={"auto" as const}
                                        loading={"lazy" as const}
                                        src={{
                                          src: "/plasmic/pg_staking/images/_3Svg.svg",
                                          fullWidth: 108,
                                          fullHeight: 150,
                                          aspectRatio: 0.719626,
                                        }}
                                      />

                                      <h4
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.h4,
                                          projectcss.__wab_text,
                                          sty.h4__oEdnl
                                        )}
                                      >
                                        {"Earn FIL for PG and yourself"}
                                      </h4>
                                    </p.Stack>
                                  ) : null}
                                </p.Stack>
                              ) : null}
                              {true ? (
                                <p.Stack
                                  as={"div"}
                                  hasGap={true}
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__jchGy
                                  )}
                                >
                                  <h2
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.h2,
                                      projectcss.__wab_text,
                                      sty.h2__fvsCb
                                    )}
                                  >
                                    {"How and where can I track this on-chain?"}
                                  </h2>
                                  <h4
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.h4,
                                      projectcss.__wab_text,
                                      sty.h4__sngks
                                    )}
                                  >
                                    <React.Fragment>
                                      <React.Fragment>
                                        {
                                          "Currently awards accumulate in publicly visible PG wallet/vault. \nThe public goods donation contract can be viewed here: 0x3bc5b7822b3a73a3f5916a590e32488dfc6f3a01 .\nAwards are held by a "
                                        }
                                      </React.Fragment>
                                      {
                                        <p.PlasmicLink
                                          className={classNames(
                                            projectcss.all,
                                            projectcss.a,
                                            projectcss.__wab_text,
                                            projectcss.plasmic_default__inline,
                                            sty.link__brzcl
                                          )}
                                          component={Link}
                                          href={
                                            "https://explorer.glif.io/address/f2w4np5xfn4rbuebllvm2kzvk4rrbgdddl7ce6hgq/?network=mainnet" as const
                                          }
                                          platform={"nextjs"}
                                        >
                                          {"multisig"}
                                        </p.PlasmicLink>
                                      }
                                      <React.Fragment>
                                        {
                                          ", which can be triggered and distributed in the following ways:\n\nExisting mechanisms:\n"
                                        }
                                      </React.Fragment>
                                      {
                                        <ul
                                          className={classNames(
                                            projectcss.all,
                                            projectcss.ul,
                                            sty.ul__suV5M
                                          )}
                                        >
                                          <li
                                            className={classNames(
                                              projectcss.all,
                                              projectcss.li,
                                              projectcss.__wab_text,
                                              sty.li___1Eb4V
                                            )}
                                          >
                                            {"Impact Evaluator"}
                                          </li>
                                          <li
                                            className={classNames(
                                              projectcss.all,
                                              projectcss.li,
                                              projectcss.__wab_text,
                                              sty.li__yWnng
                                            )}
                                          >
                                            {"IPFS PG impact fund"}
                                          </li>
                                          <li
                                            className={classNames(
                                              projectcss.all,
                                              projectcss.li,
                                              projectcss.__wab_text,
                                              sty.li__yxrek
                                            )}
                                          >
                                            {"Private Retrieval PG Impact Fund"}
                                          </li>
                                        </ul>
                                      }
                                      <React.Fragment>
                                        {"\nMechanisms under development:\n"}
                                      </React.Fragment>
                                      {
                                        <ul
                                          className={classNames(
                                            projectcss.all,
                                            projectcss.ul,
                                            sty.ul__lhEso
                                          )}
                                        >
                                          <li
                                            className={classNames(
                                              projectcss.all,
                                              projectcss.li,
                                              projectcss.__wab_text,
                                              sty.li__eXoTn
                                            )}
                                          >
                                            {"Community QV"}
                                          </li>
                                          <li
                                            className={classNames(
                                              projectcss.all,
                                              projectcss.li,
                                              projectcss.__wab_text,
                                              sty.li__aPUxb
                                            )}
                                          >
                                            {
                                              "Community-driven governance funding"
                                            }
                                          </li>
                                          <li
                                            className={classNames(
                                              projectcss.all,
                                              projectcss.li,
                                              projectcss.__wab_text,
                                              sty.li__dpaq9
                                            )}
                                          >
                                            {"S-curve funding "}
                                          </li>
                                        </ul>
                                      }
                                      <React.Fragment>{""}</React.Fragment>
                                    </React.Fragment>
                                  </h4>
                                </p.Stack>
                              ) : null}
                              {true ? (
                                <p.Stack
                                  as={"div"}
                                  hasGap={true}
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__e47Xg
                                  )}
                                >
                                  <h2
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.h2,
                                      projectcss.__wab_text,
                                      sty.h2___9Imjd
                                    )}
                                  >
                                    {"How can I get involved?"}
                                  </h2>
                                  <h4
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.h4,
                                      projectcss.__wab_text,
                                      sty.h4__jpXLk
                                    )}
                                  >
                                    <React.Fragment>
                                      <React.Fragment>
                                        {
                                          "We are already in discussion and trying to define the future roadmap, new functions, tweaking the UI UX and FAQ in the Glif discord. "
                                        }
                                      </React.Fragment>
                                      {
                                        <p.PlasmicLink
                                          className={classNames(
                                            projectcss.all,
                                            projectcss.a,
                                            projectcss.__wab_text,
                                            projectcss.plasmic_default__inline,
                                            sty.link__ulD6V
                                          )}
                                          component={Link}
                                          href={
                                            "https://discord.gg/Zx27aVn6FJ" as const
                                          }
                                          platform={"nextjs"}
                                        >
                                          {"Join us"}
                                        </p.PlasmicLink>
                                      }
                                      <React.Fragment>
                                        {" in the public-goods-pool channel."}
                                      </React.Fragment>
                                    </React.Fragment>
                                  </h4>
                                </p.Stack>
                              ) : null}
                            </p.Stack>
                          ) : null}
                        </p.Stack>
                      ) : null}
                    </div>
                  ) : null}
                </p.Stack>
                {(
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? true
                    : false
                ) ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.columns__mLfNb)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__yLgP3)}
                    >
                      {true ? (
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__oi3Vc
                          )}
                        >
                          {(
                            hasVariant(globalVariants, "screen", "mobileOnly")
                              ? true
                              : true
                          ) ? (
                            <p.PlasmicImg
                              alt={""}
                              className={classNames(sty.img__aikDz)}
                              displayHeight={"auto" as const}
                              displayMaxHeight={"none" as const}
                              displayMaxWidth={"100%" as const}
                              displayMinHeight={"0" as const}
                              displayMinWidth={"0" as const}
                              displayWidth={"8px" as const}
                              loading={"lazy" as const}
                              src={{
                                src: "/plasmic/pg_staking/images/vectorLinesvg3.svg",
                                fullWidth: 1,
                                fullHeight: 150,
                                aspectRatio: 0.004498,
                              }}
                            />
                          ) : null}
                          {true ? (
                            <p.Stack
                              as={"div"}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__aqnqF
                              )}
                            >
                              {true ? (
                                <p.Stack
                                  as={"div"}
                                  hasGap={true}
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__ip9Uk
                                  )}
                                >
                                  <h2
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.h2,
                                      projectcss.__wab_text,
                                      sty.h2___1BwtR
                                    )}
                                  >
                                    {"Process Description"}
                                  </h2>
                                  {true ? (
                                    <p.Stack
                                      as={"div"}
                                      hasGap={true}
                                      className={classNames(
                                        projectcss.all,
                                        sty.freeBox__hcaZl
                                      )}
                                    >
                                      <p.PlasmicImg
                                        alt={""}
                                        className={classNames(sty.img___05Nfo)}
                                        displayHeight={"auto" as const}
                                        displayMaxHeight={"none" as const}
                                        displayMaxWidth={"none" as const}
                                        displayMinHeight={"0" as const}
                                        displayMinWidth={"0" as const}
                                        displayWidth={"auto" as const}
                                        loading={"lazy" as const}
                                        src={{
                                          src: "/plasmic/pg_staking/images/_1Svg.svg",
                                          fullWidth: 101,
                                          fullHeight: 150,
                                          aspectRatio: 0.673077,
                                        }}
                                      />

                                      <h4
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.h4,
                                          projectcss.__wab_text,
                                          sty.h4__pKwU6
                                        )}
                                      >
                                        {
                                          "FIL Holders transfer their FIL in a Public Goods Leasing Pool which is an allocation within the GLIF Infinity Pool"
                                        }
                                      </h4>
                                    </p.Stack>
                                  ) : null}
                                  {true ? (
                                    <p.Stack
                                      as={"div"}
                                      hasGap={true}
                                      className={classNames(
                                        projectcss.all,
                                        sty.freeBox___4FEki
                                      )}
                                    >
                                      <p.PlasmicImg
                                        alt={""}
                                        className={classNames(sty.img__iflRt)}
                                        displayHeight={"auto" as const}
                                        displayMaxHeight={"none" as const}
                                        displayMaxWidth={"none" as const}
                                        displayMinHeight={"0" as const}
                                        displayMinWidth={"0" as const}
                                        displayWidth={"auto" as const}
                                        loading={"lazy" as const}
                                        src={{
                                          src: "/plasmic/pg_staking/images/_2Svg.svg",
                                          fullWidth: 109,
                                          fullHeight: 150,
                                          aspectRatio: 0.72381,
                                        }}
                                      />

                                      <h4
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.h4,
                                          projectcss.__wab_text,
                                          sty.h4__puGa
                                        )}
                                      >
                                        {
                                          "FIL will be borrowed to FIlecoin Storage Providers"
                                        }
                                      </h4>
                                    </p.Stack>
                                  ) : null}
                                  {true ? (
                                    <p.Stack
                                      as={"div"}
                                      hasGap={true}
                                      className={classNames(
                                        projectcss.all,
                                        sty.freeBox__ocklr
                                      )}
                                    >
                                      <p.PlasmicImg
                                        alt={""}
                                        className={classNames(sty.img__seO9X)}
                                        displayHeight={"auto" as const}
                                        displayMaxHeight={"none" as const}
                                        displayMaxWidth={"none" as const}
                                        displayMinHeight={"0" as const}
                                        displayMinWidth={"0" as const}
                                        displayWidth={"auto" as const}
                                        loading={"lazy" as const}
                                        src={{
                                          src: "/plasmic/pg_staking/images/_3Svg.svg",
                                          fullWidth: 108,
                                          fullHeight: 150,
                                          aspectRatio: 0.719626,
                                        }}
                                      />

                                      <h4
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.h4,
                                          projectcss.__wab_text,
                                          sty.h4__xc8SX
                                        )}
                                      >
                                        {
                                          "FIL rewards are paid out and the fee split determined by the holder will happen  automatically at time of distribution"
                                        }
                                      </h4>
                                    </p.Stack>
                                  ) : null}
                                  {true ? (
                                    <p.Stack
                                      as={"div"}
                                      hasGap={true}
                                      className={classNames(
                                        projectcss.all,
                                        sty.freeBox___2QCzr
                                      )}
                                    >
                                      <p.PlasmicImg
                                        alt={""}
                                        className={classNames(sty.img__wvb3J)}
                                        displayHeight={"auto" as const}
                                        displayMaxHeight={"none" as const}
                                        displayMaxWidth={"none" as const}
                                        displayMinHeight={"0" as const}
                                        displayMinWidth={"0" as const}
                                        displayWidth={"auto" as const}
                                        loading={"lazy" as const}
                                        src={{
                                          src: "/plasmic/pg_staking/images/_4Svg.svg",
                                          fullWidth: 116,
                                          fullHeight: 150,
                                          aspectRatio: 0.771429,
                                        }}
                                      />

                                      <h4
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.h4,
                                          projectcss.__wab_text,
                                          sty.h4__k1X1B
                                        )}
                                      >
                                        {
                                          "On-chain governance or voting by community will allocate funding utilizing Impact Evaluators to projects focusing on public goods on projects elected. To begin: IPFS, FVM and libp2p"
                                        }
                                      </h4>
                                    </p.Stack>
                                  ) : null}
                                </p.Stack>
                              ) : null}
                              {true ? (
                                <p.Stack
                                  as={"div"}
                                  hasGap={true}
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__nuome
                                  )}
                                >
                                  <h2
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.h2,
                                      projectcss.__wab_text,
                                      sty.h2__rTj4H
                                    )}
                                  >
                                    {"How do I participate?"}
                                  </h2>
                                  {true ? (
                                    <p.Stack
                                      as={"div"}
                                      hasGap={true}
                                      className={classNames(
                                        projectcss.all,
                                        sty.freeBox__bRgEe
                                      )}
                                    >
                                      <p.PlasmicImg
                                        alt={""}
                                        className={classNames(sty.img__v1Mdp)}
                                        displayHeight={"auto" as const}
                                        displayMaxHeight={"none" as const}
                                        displayMaxWidth={"none" as const}
                                        displayMinHeight={"0" as const}
                                        displayMinWidth={"0" as const}
                                        displayWidth={"auto" as const}
                                        loading={"lazy" as const}
                                        src={{
                                          src: "/plasmic/pg_staking/images/_1Svg.svg",
                                          fullWidth: 101,
                                          fullHeight: 150,
                                          aspectRatio: 0.673077,
                                        }}
                                      />

                                      <h4
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.h4,
                                          projectcss.__wab_text,
                                          sty.h4__llD1
                                        )}
                                      >
                                        {
                                          "Deposit FIL and receive an equal amount of iFIL tokens in return"
                                        }
                                      </h4>
                                    </p.Stack>
                                  ) : null}
                                  {true ? (
                                    <p.Stack
                                      as={"div"}
                                      hasGap={true}
                                      className={classNames(
                                        projectcss.all,
                                        sty.freeBox__ndU80
                                      )}
                                    >
                                      <p.PlasmicImg
                                        alt={""}
                                        className={classNames(sty.img__cw8Gh)}
                                        displayHeight={"auto" as const}
                                        displayMaxHeight={"none" as const}
                                        displayMaxWidth={"none" as const}
                                        displayMinHeight={"0" as const}
                                        displayMinWidth={"0" as const}
                                        displayWidth={"auto" as const}
                                        loading={"lazy" as const}
                                        src={{
                                          src: "/plasmic/pg_staking/images/_2Svg.svg",
                                          fullWidth: 109,
                                          fullHeight: 150,
                                          aspectRatio: 0.72381,
                                        }}
                                      />

                                      <h4
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.h4,
                                          projectcss.__wab_text,
                                          sty.h4___4Bv4
                                        )}
                                      >
                                        {"Your FIL will enter the staking pool"}
                                      </h4>
                                    </p.Stack>
                                  ) : null}
                                  {true ? (
                                    <p.Stack
                                      as={"div"}
                                      hasGap={true}
                                      className={classNames(
                                        projectcss.all,
                                        sty.freeBox__y1KhL
                                      )}
                                    >
                                      <p.PlasmicImg
                                        alt={""}
                                        className={classNames(sty.img__scXaz)}
                                        displayHeight={"auto" as const}
                                        displayMaxHeight={"none" as const}
                                        displayMaxWidth={"none" as const}
                                        displayMinHeight={"0" as const}
                                        displayMinWidth={"0" as const}
                                        displayWidth={"auto" as const}
                                        loading={"lazy" as const}
                                        src={{
                                          src: "/plasmic/pg_staking/images/_3Svg.svg",
                                          fullWidth: 108,
                                          fullHeight: 150,
                                          aspectRatio: 0.719626,
                                        }}
                                      />

                                      <h4
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.h4,
                                          projectcss.__wab_text,
                                          sty.h4__nadrs
                                        )}
                                      >
                                        {"Earn FIL for PG and yourself"}
                                      </h4>
                                    </p.Stack>
                                  ) : null}
                                </p.Stack>
                              ) : null}
                              {true ? (
                                <p.Stack
                                  as={"div"}
                                  hasGap={true}
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__meOby
                                  )}
                                >
                                  <h2
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.h2,
                                      projectcss.__wab_text,
                                      sty.h2___2PR7C
                                    )}
                                  >
                                    {"How and where can I track this on-chain?"}
                                  </h2>
                                  <h4
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.h4,
                                      projectcss.__wab_text,
                                      sty.h4__fxFgT
                                    )}
                                  >
                                    <React.Fragment>
                                      <React.Fragment>
                                        {
                                          "Currently awards accumulate in publicly visible PG wallet/vault. \nThe public goods donation contract can be viewed here: 0x3bc5b7822b3a73a3f5916a590e32488dfc6f3a01 .\nAwards are held by a "
                                        }
                                      </React.Fragment>
                                      {
                                        <p.PlasmicLink
                                          className={classNames(
                                            projectcss.all,
                                            projectcss.a,
                                            projectcss.__wab_text,
                                            projectcss.plasmic_default__inline,
                                            sty.link__aEa3H
                                          )}
                                          component={Link}
                                          href={
                                            "https://explorer.glif.io/address/f2w4np5xfn4rbuebllvm2kzvk4rrbgdddl7ce6hgq/?network=mainnet" as const
                                          }
                                          platform={"nextjs"}
                                        >
                                          {"multisig"}
                                        </p.PlasmicLink>
                                      }
                                      <React.Fragment>
                                        {
                                          ", which can be triggered and distributed in the following ways:\n\nExisting mechanisms:\n"
                                        }
                                      </React.Fragment>
                                      {
                                        <ul
                                          className={classNames(
                                            projectcss.all,
                                            projectcss.ul,
                                            sty.ul__js0Rh
                                          )}
                                        >
                                          <li
                                            className={classNames(
                                              projectcss.all,
                                              projectcss.li,
                                              projectcss.__wab_text,
                                              sty.li__qzw56
                                            )}
                                          >
                                            {"Impact Evaluator"}
                                          </li>
                                          <li
                                            className={classNames(
                                              projectcss.all,
                                              projectcss.li,
                                              projectcss.__wab_text,
                                              sty.li__uvApB
                                            )}
                                          >
                                            {"IPFS PG impact fund"}
                                          </li>
                                          <li
                                            className={classNames(
                                              projectcss.all,
                                              projectcss.li,
                                              projectcss.__wab_text,
                                              sty.li__qmqI6
                                            )}
                                          >
                                            {"Private Retrieval PG Impact Fund"}
                                          </li>
                                        </ul>
                                      }
                                      <React.Fragment>
                                        {"\nMechanisms under development:\n"}
                                      </React.Fragment>
                                      {
                                        <ul
                                          className={classNames(
                                            projectcss.all,
                                            projectcss.ul,
                                            sty.ul__vcix1
                                          )}
                                        >
                                          <li
                                            className={classNames(
                                              projectcss.all,
                                              projectcss.li,
                                              projectcss.__wab_text,
                                              sty.li___2U9Zq
                                            )}
                                          >
                                            {"Community QV"}
                                          </li>
                                          <li
                                            className={classNames(
                                              projectcss.all,
                                              projectcss.li,
                                              projectcss.__wab_text,
                                              sty.li__p0Tmp
                                            )}
                                          >
                                            {
                                              "Community-driven governance funding"
                                            }
                                          </li>
                                          <li
                                            className={classNames(
                                              projectcss.all,
                                              projectcss.li,
                                              projectcss.__wab_text,
                                              sty.li__icOi
                                            )}
                                          >
                                            {"S-curve funding "}
                                          </li>
                                        </ul>
                                      }
                                      <React.Fragment>{""}</React.Fragment>
                                    </React.Fragment>
                                  </h4>
                                </p.Stack>
                              ) : null}
                              {true ? (
                                <p.Stack
                                  as={"div"}
                                  hasGap={true}
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__mHgme
                                  )}
                                >
                                  <h2
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.h2,
                                      projectcss.__wab_text,
                                      sty.h2__h6KGi
                                    )}
                                  >
                                    {"What is the roadmap for the future?"}
                                  </h2>
                                  <h4
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.h4,
                                      projectcss.__wab_text,
                                      sty.h4__aRy3
                                    )}
                                  >
                                    {"[copy here]"}
                                  </h4>
                                </p.Stack>
                              ) : null}
                              {true ? (
                                <p.Stack
                                  as={"div"}
                                  hasGap={true}
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__qUUv
                                  )}
                                >
                                  <h2
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.h2,
                                      projectcss.__wab_text,
                                      sty.h2__jOoJ
                                    )}
                                  >
                                    {"How can I get involved?"}
                                  </h2>
                                  <h4
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.h4,
                                      projectcss.__wab_text,
                                      sty.h4___9AfKn
                                    )}
                                  >
                                    <React.Fragment>
                                      <React.Fragment>
                                        {
                                          "We are already in discussion and trying to define the future roadmap, new functions, tweaking the UI UX and FAQ in the Glif discord. "
                                        }
                                      </React.Fragment>
                                      {
                                        <p.PlasmicLink
                                          className={classNames(
                                            projectcss.all,
                                            projectcss.a,
                                            projectcss.__wab_text,
                                            projectcss.plasmic_default__inline,
                                            sty.link__hPznc
                                          )}
                                          component={Link}
                                          href={
                                            "https://discord.gg/Zx27aVn6FJ" as const
                                          }
                                          platform={"nextjs"}
                                        >
                                          {"Join us"}
                                        </p.PlasmicLink>
                                      }
                                      <React.Fragment>
                                        {" in the public-goods-pool channel."}
                                      </React.Fragment>
                                    </React.Fragment>
                                  </h4>
                                </p.Stack>
                              ) : null}
                            </p.Stack>
                          ) : null}
                        </p.Stack>
                      ) : null}
                    </div>
                    {(
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? true
                        : true
                    ) ? (
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.column__uzZzc
                        )}
                      >
                        {true ? (
                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__qXs0K
                            )}
                          >
                            <p.PlasmicImg
                              alt={""}
                              className={classNames(sty.img__loxTv)}
                              displayHeight={"auto" as const}
                              displayMaxHeight={"none" as const}
                              displayMaxWidth={"100%" as const}
                              displayMinHeight={"0" as const}
                              displayMinWidth={"0" as const}
                              displayWidth={"8px" as const}
                              loading={"lazy" as const}
                              src={{
                                src: "/plasmic/pg_staking/images/vectorLinesvg3.svg",
                                fullWidth: 1,
                                fullHeight: 150,
                                aspectRatio: 0.004498,
                              }}
                            />

                            {true ? (
                              <p.Stack
                                as={"div"}
                                hasGap={true}
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__ywDxn
                                )}
                              >
                                {true ? (
                                  <p.Stack
                                    as={"div"}
                                    hasGap={true}
                                    className={classNames(
                                      projectcss.all,
                                      sty.freeBox___9XkKw
                                    )}
                                  >
                                    <h2
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.h2,
                                        projectcss.__wab_text,
                                        sty.h2__dheU4
                                      )}
                                    >
                                      {"What is Public Goods (PG) Leasing?"}
                                    </h2>
                                    <h4
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.h4,
                                        projectcss.__wab_text,
                                        sty.h4__cqiuf
                                      )}
                                    >
                                      {
                                        "PG staking \u201cLeasing\u201d is currently running for FIL holders. We utilize GLIF. GLIF is a non-custodial automated leasing pool designed for the Filecoin network. It offers eligible Filecoin Storage Providers a convenient way to borrow FIL up to the value of the collateral they contribute to the pool. Storage Providers will make automated weekly payments back into pools, with payment amounts dynamically determined based on current market conditions. For the Public good pools-  rewards will be allocated to a public goods multisig, in which funding will be allocated by transparent on-chain tooling like Impact Evaluators and other governance tooling in a decentralized and transparent way which encourages active and clear allocation of support.  \n\n\nFollowing is an illustration of the automated Public Goods non-custodial leasing pool setup:"
                                      }
                                    </h4>
                                    <p.PlasmicImg
                                      alt={""}
                                      className={classNames(sty.img___71T30)}
                                      displayHeight={"auto" as const}
                                      displayMaxHeight={"none" as const}
                                      displayMaxWidth={"100%" as const}
                                      displayMinHeight={"0" as const}
                                      displayMinWidth={"0" as const}
                                      displayWidth={"auto" as const}
                                      loading={"lazy" as const}
                                      src={{
                                        src: "/plasmic/pg_staking/images/glifBlogpost1Png2.png",
                                        fullWidth: 532,
                                        fullHeight: 379,
                                        aspectRatio: undefined,
                                      }}
                                    />
                                  </p.Stack>
                                ) : null}
                                {true ? (
                                  <p.Stack
                                    as={"div"}
                                    hasGap={true}
                                    className={classNames(
                                      projectcss.all,
                                      sty.freeBox__xkmij
                                    )}
                                  >
                                    <h2
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.h2,
                                        projectcss.__wab_text,
                                        sty.h2__zwd0Z
                                      )}
                                    >
                                      {"Why do this on chain?"}
                                    </h2>
                                    <h4
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.h4,
                                        projectcss.__wab_text,
                                        sty.h4__z4Ppp
                                      )}
                                    >
                                      {
                                        "Traditional off chain models for funding include grants and funding allocation channels like crowdfunding, foundations and developer awards. These often lack transparency and are decided by a central entity. Payment times can vary from a few weeks to several months or even years. Community and ecosystem developers do not typically have access to the tracing or transparency of funding or what teams are allocated how much and when. The thesis of restructuring funding to onchain mechanism means that much of these delays and lack of transparency are theoretically eliminated. Once a voting round closes, team allocations are automatically done- this means that payments happen faster, teams can accelerate and scale accordingly without dependency on additional parties. "
                                      }
                                    </h4>
                                  </p.Stack>
                                ) : null}
                                {true ? (
                                  <p.Stack
                                    as={"div"}
                                    hasGap={true}
                                    className={classNames(
                                      projectcss.all,
                                      sty.freeBox__jgaQ5
                                    )}
                                  >
                                    <h2
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.h2,
                                        projectcss.__wab_text,
                                        sty.h2__cbXtL
                                      )}
                                    >
                                      {"What is iFil?"}
                                    </h2>
                                    <h4
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.h4,
                                        projectcss.__wab_text,
                                        sty.h4__y8W34
                                      )}
                                    >
                                      {
                                        "When a FIL token holder deposits FIL into the Infinity Pool, they receive iFIL tokens in return. iFIL is the native liquid staking token for filecoin - iFIL can be transferred to other wallets, traded on secondaries, and used in other DeFi protocols. The price of iFIL is calculated as: \n     iFIL price = Glif Infinity Pool total assets / iFIL circulating supply \n\nThe initial price of iFIL to FIL is 1 : 1, but this will change once the borrowing side of the Infinity Pool opens to SPs. When the Infinity Pool receives its weekly payment from an SP, the Infinity Pool's total assets increase, which increases the value of iFIL in terms of FIL. When a Staker deposits FIL in the pool, they get back a proportionate amount of iFIL determined by the current iFIL price at that point in time:\n     iFIL received = FIL stake / current iFIL price \n\nAs the price of iFIL increases, the amount of iFIL received per FIL stake decreases."
                                      }
                                    </h4>
                                  </p.Stack>
                                ) : null}
                              </p.Stack>
                            ) : null}
                          </p.Stack>
                        ) : null}
                      </p.Stack>
                    ) : null}
                  </p.Stack>
                ) : null}
              </p.Stack>
            </div>
            <Footer
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames("__wab_instance", sty.footer)}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "header", "h6", "footer"],
  header: ["header"],
  h6: ["h6"],
  footer: ["footer"],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: typeof Header;
  h6: "h6";
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFaQs__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFaQs__VariantsArgs;
    args?: PlasmicFaQs__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicFaQs__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicFaQs__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicFaQs__ArgProps,
          internalVariantPropNames: PlasmicFaQs__VariantProps,
        }),
      [props, nodeName]
    );
    return PlasmicFaQs__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFaQs";
  } else {
    func.displayName = `PlasmicFaQs.${nodeName}`;
  }
  return func;
}

export const PlasmicFaQs = Object.assign(
  // Top-level PlasmicFaQs renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    h6: makeNodeComponent("h6"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicFaQs
    internalVariantProps: PlasmicFaQs__VariantProps,
    internalArgProps: PlasmicFaQs__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Public Goods Funding - FAQ",
      description: "",
      ogImageSrc: "",
      canonical: "",
    },
  }
);

export default PlasmicFaQs;
/* prettier-ignore-end */
